#!/bin/bash

# Check if variables exist
zookeeper_url=${CONNECT_ZOOKEEPER_CONNECT:?}
schema_url=${CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL:?}
num_brokers=${KAFKA_BROKERS:-3}

max_timeout=32

tries=10
timeout=1
while true; do
    ZOOKEEPER_CHECK=$(zookeeper-shell ${zookeeper_url} <<< "ls /brokers/ids" | tail -2 | head -1)
    echo "Zookeeper response: ${ZOOKEEPER_CHECK}"
    # ZOOKEEPER_CHECK="${ZOOKEEPER_CHECK##*$'\n'}"
    ZOOKEEPER_CHECK="$(echo -e "${ZOOKEEPER_CHECK}" | tr -d '[:space:]'  | tr -d '['  | tr -d ']')"

    IFS=',' read -r -a array <<< ${ZOOKEEPER_CHECK}
    LENGTH=${#array[@]}
    if [ "$LENGTH" -eq "$num_brokers" ]; then
        echo "Kafka brokers available."
        break
    fi

    tries=$((tries - 1))
    if [ ${tries} -eq 0 ]; then
        echo "FAILED: KAFKA BROKERs NOT READY."
        exit 5
    fi
    echo "Expected $num_brokers brokers but found only $LENGTH. Waiting $timeout second before retrying ..."
    sleep ${timeout}
    if [ ${timeout} -lt ${max_timeout} ]; then
        timeout=$((timeout * 2))
    fi
done

tries=10
timeout=1
while true; do
    if wget --spider -q "${schema_url}/subjects" 2>/dev/null; then
        echo "Schema registry available."
        break
    fi
    tries=$((tries - 1))
    if [ $tries -eq 0 ]; then
        echo "FAILED TO REACH SCHEMA REGISTRY."
        exit 6
    fi
    echo "Failed to reach schema registry. Retrying in ${timeout} seconds."
    sleep ${timeout}
    if [ ${timeout} -lt ${max_timeout} ]; then
        timeout=$((timeout * 2))
    fi
done


echo "Kafka is available. Ready to go!"
